### ISSUE TITLE
Exception when remote following

### ISSUE THREAD

**Issue by jcgruenhage** [tsileo/microblog.pub#10]
When I try to follow people from mastodon, I get an exception:

```
web_1     | [2018-06-24 12:37:30 +0000] [12] [DEBUG] GET /authorize_follow
web_1     | [2018-06-24 12:37:32 +0000] [11] [DEBUG] POST /authorize_follow
web_1     | [2018-06-24 12:37:32 +0000] [11] [INFO] performing webfinger resolution for Gargron@mastodon.social
web_1     | [2018-06-24 12:37:32 +0000] [11] [DEBUG] check_url https://mastodon.social debug=False
web_1     | [2018-06-24 12:37:32 +0000] [11] [DEBUG] dns lookup: mastodon.social -> 136.243.102.156
web_1     | [2018-06-24 12:37:32 +0000] [11] [DEBUG] 136.243.102.156
web_1     | [2018-06-24 12:37:32 +0000] [11] [DEBUG] check_url https://mastodon.social/.well-known/webfinger debug=False
web_1     | [2018-06-24 12:37:32 +0000] [11] [DEBUG] Starting new HTTPS connection (1): mastodon.social:443
web_1     | [2018-06-24 12:37:32 +0000] [11] [DEBUG] https://mastodon.social:443 "GET /.well-known/webfinger?resource=acct%3AGargron%40mastodon.social HTTP/1.1" 200 None
web_1     | [2018-06-24 12:37:32 +0000] [11] [DEBUG] check_url http://mastodon.social/.well-known/webfinger debug=False
web_1     | [2018-06-24 12:37:32 +0000] [11] [DEBUG] Starting new HTTP connection (1): mastodon.social:80
web_1     | [2018-06-24 12:37:32 +0000] [11] [DEBUG] http://mastodon.social:80 "GET /.well-known/webfinger?resource=acct%3AGargron%40mastodon.social HTTP/1.1" 301 194
web_1     | [2018-06-24 12:37:32 +0000] [11] [DEBUG] Starting new HTTPS connection (1): mastodon.social:443
web_1     | [2018-06-24 12:37:33 +0000] [11] [DEBUG] https://mastodon.social:443 "GET /.well-known/webfinger?resource=acct%3AGargron%40mastodon.social HTTP/1.1" 200 None
web_1     | [2018-06-24 12:37:33 +0000] [11] [ERROR] Exception on /authorize_follow [POST]
web_1     | Traceback (most recent call last):
web_1     |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
web_1     |     response = self.full_dispatch_request()
web_1     |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
web_1     |     rv = self.handle_user_exception(e)
web_1     |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
web_1     |     reraise(exc_type, exc_value, tb)
web_1     |   File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
web_1     |     raise value
web_1     |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
web_1     |     rv = self.dispatch_request()
web_1     |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
web_1     |     return self.view_functions[rule.endpoint](**req.view_args)
web_1     |   File "/app/app.py", line 249, in decorated_function
web_1     |     return f(*args, **kwargs)
web_1     |   File "/app/app.py", line 400, in authorize_follow
web_1     |     follow = activitypub.Follow(actor=MY_PERSON.id, object=actor)
web_1     | AttributeError: module 'activitypub' has no attribute 'Follow'
```

**Comment by dsblank** [comment]
I think the line should be:

```python
ap.Follow(actor=MY_PERSON.id, object=actor)
```
after the recent split to little_boxes.

**Comment by jcgruenhage** [comment]
@tsileo I have no problem with being an early tester, happy to help. Good job so far

**Comment by tsileo** [comment]
Thank you!

This week I'm planning to work more on the admin UI because right now it's quite unusable as I been mostly focused on the public frontend.
