### ISSUE TITLE
syntax error in _GRIDFS_CACHE

### ISSUE THREAD

**Issue by bhaugen** [tsileo/microblog.pub#46]
installed and running locally to try it out.
Error traceback:
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/cli.py", line 325, in __call__
    self._flush_bg_loading_exception()
  File "/usr/local/lib/python2.7/dist-packages/flask/cli.py", line 313, in _flush_bg_loading_exception
    reraise(*exc_info)
  File "/usr/local/lib/python2.7/dist-packages/flask/cli.py", line 302, in _load_app
    self._load_unlocked()
  File "/usr/local/lib/python2.7/dist-packages/flask/cli.py", line 317, in _load_unlocked
    self._app = rv = self.loader()
  File "/usr/local/lib/python2.7/dist-packages/flask/cli.py", line 372, in load_app
    app = locate_app(self, import_name, name)
  File "/usr/local/lib/python2.7/dist-packages/flask/cli.py", line 235, in locate_app
    __import__(module_name)
File "/home/lemur/microblog.pub/app.py", line 224
    _GRIDFS_CACHE: Dict[Tuple[Kind, str, Optional[int]], str] = {}
                 ^
SyntaxError: invalid syntax
```
P.S. I'm running Ubuntu 16.04. And I know this is still work in process, so I am not in a hurry for anything, just checking it out.

**Comment by tsileo** [comment]
Microblog.pub needs Python3.7+.

Thanks.
