### ISSUE TITLE
Post with location but no latitude throws 500 Error

### ISSUE THREAD

**Issue by inhji** [tsileo/microblog.pub#66]
I can't access my stream right now. I assume there is some post that has a location but doesn't have the latitude field filled.

```
[2019-12-09 07:28:02 +0000] [39] [ERROR] Exception on /admin/stream [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/core/shared.py", line 121, in decorated_function
    return f(*args, **kwargs)
  File "/app/blueprints/admin.py", line 554, in admin_stream
    tpl, inbox_data=inbox_data, older_than=older_than, newer_than=newer_than
  File "/usr/local/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/usr/local/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/app/templates/stream.html", line 2, in top-level template code
    {% import 'utils.html' as utils %}
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "/app/templates/stream.html", line 17, in root
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
  File "/app/templates/layout.html", line 125, in root
    $navbarBurgers.forEach( el => {
  File "/app/templates/stream.html", line 248, in block_content
  File "/usr/local/lib/python3.7/site-packages/jinja2/runtime.py", line 262, in call
    return __obj(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/jinja2/runtime.py", line 570, in __call__
    return self._invoke(arguments, autoescape)
  File "/usr/local/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 110, in _invoke
    return original_invoke(self, arguments, autoescape)
  File "/usr/local/lib/python3.7/site-packages/jinja2/runtime.py", line 574, in _invoke
    rv = self._func(*arguments)
  File "/app/templates/utils.html", line 637, in macro
  File "/app/utils/template_filters.py", line 266, in get_place
    lat = tag["latitude"]
KeyError: 'latitude'
[2019-12-09 07:28:02 +0000] [39] [ERROR] caught error <InternalServerError '500: Internal Server Error'>, 
```

**Comment by inhji** [comment]
I opened #68 to fix this

**Comment by tsileo** [comment]
Fixed by your PR, thanks!
