### ISSUE TITLE
Suddenly getting 500 error on /admin/stream

### ISSUE THREAD

**Issue by Bradshaw** [tsileo/microblog.pub#91]
Everything was working fine yesterday and has been working for months.  
As of this morning I'm getting a 500 error on /admin/stream.
This is what prints for `docker logs microblogpug_web_1`:
```Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app‧py", line 2447, in wsgi_app
    response = self‧full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app‧py", line 1952, in full_dispatch_request
    rv = self‧handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app‧py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat‧py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app‧py", line 1950, in full_dispatch_request
    rv = self‧dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app‧py", line 1936, in dispatch_request
    return self‧view_functions[rule‧endpoint](**req‧view_args)
  File "/app/core/shared‧py", line 121, in decorated_function
    return f(*args, **kwargs)
  File "/app/blueprints/admin‧py", line 554, in admin_stream
    tpl, inbox_data=inbox_data, older_than=older_than, newer_than=newer_than
  File "/usr/local/lib/python3.7/site-packages/flask/templating‧py", line 140, in render_template
    ctx‧app,
  File "/usr/local/lib/python3.7/site-packages/flask/templating‧py", line 120, in _render
    rv = template‧render(context)
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment‧py", line 1090, in render
    self‧environment‧handle_exception()
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment‧py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/local/lib/python3.7/site-packages/jinja2/_compat‧py", line 28, in reraise
    raise value‧with_traceback(tb)
  File "/app/templates/stream.html", line 2, in top-level template code
    {% import 'utils.html' as utils %}
  File "/app/templates/layout.html", line 55, in top-level template code
    {% block content %}{% endblock %}
  File "/app/templates/stream.html", line 163, in block "content"
    {{ utils‧display_note(item‧meta‧object, meta=item‧meta) }}
  File "/usr/local/lib/python3.7/site-packages/jinja2/runtime‧py", line 679, in _invoke
    rv = self._func(*arguments)
  File "/app/templates/utils.html", line 242, in template
    {% for a in (obj | iter_note_attachments) %}
  File "/app/utils/template_filters‧py", line 453, in iter_note_attachments
    return [a for a in attachments if a‧get("url") not in imgs]
  File "/app/utils/template_filters‧py", line 453, in <listcomp>
    return [a for a in attachments if a‧get("url") not in imgs]
AttributeError: 'str' object has no attribute 'get'
[2021-02-09 09:38:25 +0100] [38] [ERROR] caught error <InternalServerError '500: Internal Server Error'>,```

Any help getting this working again would be greatly appreciated

**Comment by Bradshaw** [comment]
In case it's at all relevant, this is my configuration: https://github.com/Bradshaw/microblog.pub/tree/mine

**Comment by Bradshaw** [comment]
Okay, update:
Now the error 500 is happening on page 2 of the stream. I assume there's a post in the stream that is causing an issue when it's being prepared for display, which is no longer on the first page.

**Comment by tsileo** [comment]
Hey, thanks for the report, I have seen this happening too, it looks like some attachments are "embedded object IRI/URI" instead of the object itself.
I will keep you updated!
